keys:
  - id: user-0
    port: 9000
    cipher: chacha20-ietf-poly1305
    secret: Secret0

  - id: user-1
    port: 9000
    cipher: chacha20-ietf-poly1305
    secret: Secret1

  - id: user-2
    port: 9001
    cipher: chacha20-ietf-poly1305
    secret: Secret2
    traffic_limits:
      large_scale_limit: 100000000000
      large_scale_period: "30d"
      small_scale_limit: 12800000000
      small_scale_period: "1s"

default_traffic_limits:
  large_scale_limit: 2000000000
  large_scale_period: "30d"
  small_scale_limit: 128000000
  small_scale_period: "1s"
