keys:
  - id: user-0
    port: 9000
    cipher: chacha20-ietf-poly1305
    secret: Secret0

  - id: user-1
    port: 9000
    cipher: chacha20-ietf-poly1305
    secret: Secret1

  - id: user-2
    port: 9001
    cipher: chacha20-ietf-poly1305
    secret: Secret2


services:
  - listeners:
    - type: tcp
      address: 0.0.0.0:8080
    - type: udp
      address: 0.0.0.0:8080
    - type: proxyproto
      listener:
        type: tcp
        address: 0.0.0.0:8081
    - type: proxyproto
      listener:
        type: udp
        address: 0.0.0.0:8081