services:
  - listeners:
      # TODO(sbruens): Allow a string-based listener config, as a convenient short-form
      # to create a direct listener, e.g. `- tcp/[::]:9000`.
      - type: tcp
        address: "[::]:9000"
      - type: udp
        address: "[::]:9000"
    keys:
        - id: user-0
          cipher: chacha20-ietf-poly1305
          secret: Secret0
        - id: user-1
          cipher: chacha20-ietf-poly1305
          secret: Secret1

  - listeners:
      - type: tcp
        address: "[::]:9001"
      - type: udp
        address: "[::]:9001"
    keys:
        - id: user-2
          cipher: chacha20-ietf-poly1305
          secret: Secret2
