name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: '${{ github.workspace }}/go.mod'

    - name: Get dependencies
      run: |
        # Download GeoIP test data from MaxMind
        git submodule update --init

    - name: Build
      run: go build -v ./...

    - name: Check licenses
      # We allow only "notice" type of licenses.
      run: go run github.com/google/go-licenses check --ignore=golang.org/x --allowed_licenses=Apache-2.0,Apache-3,BSD-3-Clause,BSD-4-Clause,CC0-1.0,ISC,MIT ./...

    - name: Test
      run: go test -race -benchmem -bench=. ./... -benchtime=100ms
